version: "3.7"

services:
  server:
    image: yodaskillme/redis-app
    ports:
      - 5010:5010
    networks:
      net:
    environment:
      REDIS_HOST: 172.26.0.2

  database:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - data:/data
    networks:
      net:
        ipv4_address: 172.26.0.2

volumes:
  data:

networks:
  net:
    ipam:
      config:
        - subnet: 172.26.0.0/16